<h1>Importing the necessary data</h1>

In [11]:
import numpy as np
import plotly.express as px
from sklearn.preprocessing import StandardScaler

<h1>Defining the data that will be used to perform the grouping</h1>

In [12]:
x = [20, 27, 21, 37, 46, 53, 55, 47, 52, 32, 39, 41, 39, 48, 48]
y = [1000, 1200, 2900, 1850, 900, 950, 2000, 2100, 3000, 5900, 4100, 5100, 7000, 5000, 6500]

In [13]:
base = np.array(
    [
        [20, 1000],
        [27, 1200],
        [21, 2900],
        [37, 1850],
        [46, 900],
        [53, 950],
        [55, 2000],
        [47, 2100],
        [52, 3000],
        [32, 5900],
        [39, 4100],
        [41, 5100],
        [39, 7000],
        [48, 5000],
        [48, 6500]
    ]
)

In [14]:
base

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

<h1>Scalling data</h1>

In [15]:
scaler = StandardScaler()
base_scaled = scaler.fit_transform(base)

In [16]:
base_scaled

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

<h1>Creating clustering with DBSCAN</h1>

In [17]:
from sklearn.cluster import DBSCAN

In [18]:
dbscan = DBSCAN(eps=0.95, min_samples=2)
dbscan.fit(base_scaled)

DBSCAN(eps=0.95, min_samples=2)

<h1>Showing grouping results</h1>

In [19]:
labels = dbscan.labels_
labels

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], dtype=int64)

In [20]:
grafic = px.scatter(x = base[:,0], y = base[:,1], color=labels)
grafic.show()