<h1>Importing libraries and necessary data</h1>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('house_prices.csv')

In [3]:
df

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

<h1>Separating predictive data from classes</h1>

In [4]:
x_houses = df.iloc[:,3:19].values
y_houses = df.iloc[:,2].values

In [5]:
from sklearn.model_selection import train_test_split
x_houses_train, x_houses_test, y_houses_train, y_houses_test = train_test_split(x_houses, y_houses, test_size=0.3, random_state=0)

In [6]:
x_houses_train.shape, x_houses_test.shape

((15129, 16), (6484, 16))

In [7]:
x_houses_train

array([[ 4.00000e+00,  1.50000e+00,  1.39000e+03, ...,  9.81330e+04,
         4.77224e+01, -1.22332e+02],
       [ 3.00000e+00,  1.50000e+00,  1.45000e+03, ...,  9.81330e+04,
         4.77725e+01, -1.22349e+02],
       [ 5.00000e+00,  2.75000e+00,  2.86000e+03, ...,  9.80520e+04,
         4.77082e+01, -1.22104e+02],
       ...,
       [ 3.00000e+00,  2.25000e+00,  2.36000e+03, ...,  9.80420e+04,
         4.73856e+01, -1.22158e+02],
       [ 4.00000e+00,  2.00000e+00,  2.37000e+03, ...,  9.80010e+04,
         4.72831e+01, -1.22279e+02],
       [ 4.00000e+00,  2.25000e+00,  2.38000e+03, ...,  9.80080e+04,
         4.76126e+01, -1.22120e+02]])

In [8]:
y_houses_train

array([400000., 430000., 720000., ..., 431000., 411000., 699900.])

<h1>Scalling data</h1>

In [9]:
from sklearn.preprocessing import StandardScaler

scaler_x = StandardScaler()
x_houses_train_scaled = scaler_x.fit_transform(x_houses_train)

scaler_y = StandardScaler()
y_houses_train_scaled = scaler_y.fit_transform(y_houses_train.reshape(-1,1))

In [10]:
x_houses_train_scaled

array([[ 0.67170039, -0.79711466, -0.74522967, ...,  1.03727271,
         1.17348387, -0.83797629],
       [-0.38696772, -0.79711466, -0.68028398, ...,  1.03727271,
         1.53476983, -0.95879989],
       [ 1.7303685 ,  0.82292131,  0.84593978, ..., -0.48008241,
         1.07108346,  0.78248142],
       ...,
       [-0.38696772,  0.17490692,  0.30472568, ..., -0.66741021,
        -1.25528083,  0.3986888 ],
       [ 0.67170039, -0.14910028,  0.31554996, ..., -1.43545415,
        -1.99443873, -0.46129094],
       [ 0.67170039,  0.17490692,  0.32637425, ..., -1.3043247 ,
         0.38168351,  0.66876509]])

In [11]:
y_houses_train_scaled

array([[-0.38454326],
       [-0.3024967 ],
       [ 0.49062008],
       ...,
       [-0.29976181],
       [-0.35445952],
       [ 0.43564888]])

In [12]:
x_houses_test_scaled = scaler_x.transform(x_houses_test)
y_houses_test_scaled = scaler_y.fit_transform(y_houses_test.reshape(-1,1))

In [13]:
x_houses_test_scaled

array([[-1.44563583, -0.79711466, -0.70193254, ...,  0.88741047,
         1.17204161, -0.53947092],
       [ 0.67170039,  1.47093569,  2.80513482, ..., -1.36052304,
         0.54321655,  0.35604518],
       [-1.44563583, -1.76913625, -0.69110826, ...,  0.55022044,
         0.80065984, -1.06540895],
       ...,
       [-0.38696772,  0.49891411,  0.07741576, ..., -0.36768574,
        -0.78077751,  0.88909048],
       [-0.38696772, -0.47310747, -0.64781113, ..., -0.854738  ,
        -1.39878563, -0.46839822],
       [-0.38696772, -1.44512905, -0.82099964, ...,  0.26922876,
        -1.78603226,  0.22100704]])

In [14]:
y_houses_test_scaled

array([[-0.65279094],
       [ 2.80442566],
       [ 0.06267207],
       ...,
       [-0.42878706],
       [-0.73105736],
       [-0.89838556]])

<h1>Training the algorithm with separate data</h1>

In [15]:
from sklearn.svm import SVR

regressor_rbf = SVR(kernel='rbf')
regressor_rbf.fit(x_houses_train_scaled, y_houses_train_scaled.ravel())

SVR()

In [16]:
regressor_rbf.score(x_houses_train_scaled, y_houses_train_scaled)

0.8123337393147001

In [17]:
regressor_rbf.score(x_houses_test_scaled, y_houses_test_scaled)

0.7389491788167484

In [18]:
predicts = regressor_rbf.predict(x_houses_test_scaled)
predicts

array([-0.54571552,  3.46454238,  0.02286424, ..., -0.46405796,
       -0.91113329, -1.03334346])

In [19]:
y_houses_test_scaled

array([[-0.65279094],
       [ 2.80442566],
       [ 0.06267207],
       ...,
       [-0.42878706],
       [-0.73105736],
       [-0.89838556]])

In [20]:
y_houses_test_inverse = scaler_y.inverse_transform(y_houses_test_scaled)
predicts_inverse = scaler_y.inverse_transform(predicts.reshape(-1,1))

In [21]:
y_houses_test_inverse

array([[ 297000.],
       [1578000.],
       [ 562100.],
       ...,
       [ 380000.],
       [ 268000.],
       [ 206000.]])

In [22]:
predicts_inverse

array([[ 336674.58052943],
       [1822592.57569077],
       [ 547350.03078744],
       ...,
       [ 366931.0955898 ],
       [ 201276.59358333],
       [ 155994.1481581 ]])

In [23]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_houses_test_inverse, predicts_inverse)

82469.31542833184